# spring.datasource.url=jdbc:mysql://localhost:3306/react_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=Ameya@123
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# fall back to local/public proxy if MYSQL* env vars are missing
spring.datasource.url=jdbc:mysql://${MYSQLHOST:mainline.proxy.rlwy.net}:${MYSQLPORT:47527}/${MYSQLDATABASE:railway}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:buVsVzjXpgWAdqvPSMharNXxaUmPYwkX}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect